<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Вход</name>
   <tag></tag>
   <elementGuidId>462d8277-fd22-4832-805f-7b6d8aeefecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/w/sign-in' and (text() = 'Вход' or . = 'Вход')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeLarge.MuiButton-outlinedSizeLarge.MuiButton-disableElevation.MuiButtonBase-root.css-b2bmev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '/w/sign-in' and (text() = 'Вход' or . = 'Вход')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94571056-bd22-4a8f-89e4-5fca1818935c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeLarge MuiButton-outlinedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-b2bmev</value>
      <webElementGuid>052750f6-b6a7-434d-bce8-e300a9316f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>852a930c-2a59-4663-a616-264f89a68a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/w/sign-in</value>
      <webElementGuid>8fec001c-472b-4652-84ac-c832af59ac3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Вход</value>
      <webElementGuid>36103114-4430-497b-80ba-5c0aea495b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/div[@class=&quot;MuiBox-root css-y173z4-Landing-root&quot;]/header[@class=&quot;MuiBox-root css-r6qb13-LandingHeader-root&quot;]/div[@class=&quot;MuiBox-root css-69i1ev&quot;]/header[@class=&quot;css-1qgvkyg-Header-root-LandingHeader-header&quot;]/div[@class=&quot;MuiBox-root css-zdpt2t&quot;]/a[@class=&quot;MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeLarge MuiButton-outlinedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-b2bmev&quot;]</value>
      <webElementGuid>4c599f53-a088-488c-a84f-68de3bfb70a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/header/div/header/div/a</value>
      <webElementGuid>5179b4db-71cf-48f9-b441-73e258231224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Вход')]</value>
      <webElementGuid>53cdfcce-6a0f-4465-8428-f0ed1c82a1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Бета версия'])[1]/following::a[1]</value>
      <webElementGuid>06f1e997-521d-4385-979e-a05d1a5f073d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Студио для подкастеров'])[2]/preceding::a[1]</value>
      <webElementGuid>3ee4e420-b9e8-438f-ad6b-ea4586c8c71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Рассказывайте истории — мы позаботимся, чтобы они были всегда доступны и нашли свою аудиторию'])[1]/preceding::a[1]</value>
      <webElementGuid>d19ef074-17cf-4913-88a6-12fe5e25d9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Вход']/parent::*</value>
      <webElementGuid>0b294a0d-d150-42c3-80a5-f3e6a544e09a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/w/sign-in')]</value>
      <webElementGuid>4dee9510-f3b9-4c17-83ef-e047a9eaa63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>f8e1d124-f3aa-46a4-a472-e2530aecba98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/w/sign-in' and (text() = 'Вход' or . = 'Вход')]</value>
      <webElementGuid>6b9ee168-33f8-44c0-a92d-5b4afe74a487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
