<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Зарегистрироваться</name>
   <tag></tag>
   <elementGuidId>2c829605-c407-4462-8d36-60e7aeedfeb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href = '/w#reg' and (text() = 'Зарегистрироваться' or . = 'Зарегистрироваться')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.MuiTypography-root.MuiTypography-p4.MuiLink-root.MuiLink-underlineNone.css-d6d3zt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>beaf548a-e8f2-4f1e-a935-22eb74b55c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-p4 MuiLink-root MuiLink-underlineNone css-d6d3zt</value>
      <webElementGuid>7fe40081-f237-4dc8-b514-3431f2081b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/w#reg</value>
      <webElementGuid>a543be2b-0d58-4b6b-b338-2c83ed1669d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Зарегистрироваться</value>
      <webElementGuid>e332f422-09c7-4161-9bc8-9d23aef7332c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-1xprv68-Main-root-Auth-Main-root&quot;]/div[@class=&quot;Ui-Container-withPadding MuiBox-root css-mrz6wc-Ui-Container-root&quot;]/div[@class=&quot;css-a2qr2c-Ui-Container-inner&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded css-e8dape-Auth-Main-paper&quot;]/form[1]/div[@class=&quot;css-btzsx8&quot;]/a[@class=&quot;MuiTypography-root MuiTypography-p4 MuiLink-root MuiLink-underlineNone css-d6d3zt&quot;]</value>
      <webElementGuid>362d5a35-e444-42b5-8725-200d50510eb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/form/div[5]/a</value>
      <webElementGuid>9b0243c6-9c8a-4c3c-aa30-a97cba151aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Зарегистрироваться')]</value>
      <webElementGuid>e7ac52c2-1853-4e8b-ab0f-ea11e15097a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Впервые в Студио для подкастеров?'])[1]/following::a[1]</value>
      <webElementGuid>d9b333b8-8172-42b1-a551-7543b2a43e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Забыли пароль?'])[1]/following::a[1]</value>
      <webElementGuid>3bde72f9-d89e-45b9-aec5-134a29199a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/w#reg')])[2]</value>
      <webElementGuid>95843173-9eea-4cdf-893f-d3b28fb502b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>b8325c30-5073-4f50-a994-aa0d9454b719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/w#reg' and (text() = 'Зарегистрироваться' or . = 'Зарегистрироваться')]</value>
      <webElementGuid>6865242f-1c4d-40f2-b4bd-7d3628732312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
