<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Зарегистрироваться2</name>
   <tag></tag>
   <elementGuidId>a5770c4c-fda4-4e54-a4d2-4b0f99244d3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/header/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-vide34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>308afa0d-988f-41bd-a914-c098f9310cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-vide34</value>
      <webElementGuid>9a05d2ef-23ce-4a72-b665-c2559a88031b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Зарегистрироваться</value>
      <webElementGuid>771bfa83-4b36-4562-8a7f-7978b0ca5160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/header[@class=&quot;css-1c7j3ft-Header-root-UnauthorizedHeader-root&quot;]/div[@class=&quot;css-1qvs8f0&quot;]/a[@class=&quot;MuiTypography-root MuiTypography-p4 MuiLink-root MuiLink-underlineNone css-464ltv&quot;]/div[@class=&quot;css-vide34&quot;]</value>
      <webElementGuid>8af56a64-8cc3-4b91-b876-c38c7ed91522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/header/div/a/div</value>
      <webElementGuid>37b657b0-4a81-4645-94eb-d69362764dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Вход'])[2]/preceding::div[3]</value>
      <webElementGuid>f054f906-826e-4e7c-8b24-9e2e7d8365b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>6838eafa-38a6-4fe1-895c-84c885249451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Зарегистрироваться' or . = 'Зарегистрироваться')]</value>
      <webElementGuid>c9fc16d7-bf52-44bb-8ba3-46edd579a042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
