<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Заголовок</name>
   <tag></tag>
   <elementGuidId>db96f350-f37e-4b1d-b9eb-ddef5fdd2862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8eb70819-2c63-4894-bb2b-d85647000354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>e5b713ad-1e15-4cd1-95c0-aae3abd75f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tr</name>
      <type>Main</type>
      <value>your_tempmail_address_is_ready</value>
      <webElementGuid>6394217e-2bdd-48dd-a5cb-150d01abeab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your tempmail address is ready</value>
      <webElementGuid>8f35bfef-def8-4337-abc4-997a822ecc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email&quot;)/h2[@class=&quot;title&quot;]</value>
      <webElementGuid>7f53a62d-b42c-4ed2-bfd8-e3f19f4c1ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email']/h2</value>
      <webElementGuid>4de0fd5d-4a3e-47d0-8ffa-28a156f55db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::h2[1]</value>
      <webElementGuid>c7c80e2d-e9c9-44d8-b4eb-1833b91502e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/following::h2[1]</value>
      <webElementGuid>676a876a-a094-4bc1-91a5-e63fc5885e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@mailto.plus'])[1]/preceding::h2[1]</value>
      <webElementGuid>3c92d5e7-26ef-4d0e-b58e-602b6e11877f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mailto.plus'])[1]/preceding::h2[1]</value>
      <webElementGuid>1099bba3-c7b5-4d1b-8cd7-99d8bcaf3e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your tempmail address is ready']/parent::*</value>
      <webElementGuid>19aa0086-3612-4440-8ab4-1b2901db2c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>fae32a9a-c390-4f7f-92ae-be133a71142e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Your tempmail address is ready' or . = 'Your tempmail address is ready')]</value>
      <webElementGuid>db8adc6c-7e51-40d6-b573-73a44da24ae8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
