<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Настроить дистрибуцию</name>
   <tag></tag>
   <elementGuidId>8baa3d94-cd4f-41ac-bf76-fabee05bce27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-disableElevation.MuiButtonBase-root.css-1gqqfnd-Episodes-DistributionSuggest-addButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Настроить')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>21385c6d-63fe-4fd8-a262-dbb3ca5cb7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-1gqqfnd-Episodes-DistributionSuggest-addButton</value>
      <webElementGuid>2ac34f1f-ea48-46f8-9609-f81ae78cc5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5505c649-a90f-474a-b205-54cd93911959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>tune-button</value>
      <webElementGuid>75e43411-d344-45aa-a9cf-3585ec2ea12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/w/podcast/21380/settings/distribution</value>
      <webElementGuid>4fbfa4e8-6f3c-4259-8cdc-2f38d607874a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Настроить</value>
      <webElementGuid>0a97aa23-9670-47b3-8417-98293c1bba10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-pr5jul-Main-root&quot;]/div[@class=&quot;Ui-Container-withPadding DistributionSuggest-root MuiBox-root css-nil75h-Ui-Container-root-Episodes-DistributionSuggest-root&quot;]/div[@class=&quot;css-yqbj2u-Ui-Container-inner&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded css-hqipaq&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-undefined css-xswmv4-Episodes-DistributionSuggest-content&quot;]/a[@class=&quot;MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-1gqqfnd-Episodes-DistributionSuggest-addButton&quot;]</value>
      <webElementGuid>f5b3e548-7985-4b38-80bf-4f12565fd237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/div/a</value>
      <webElementGuid>2fdf7ca1-d514-4d18-84bf-57bd566da0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Настроить')]</value>
      <webElementGuid>53cbad54-74a1-456d-be49-c110d1b8c54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выберите, на каких площадках вы хотите опубликовать свой подкаст'])[1]/following::a[1]</value>
      <webElementGuid>62cf9e5c-efb3-4773-93e1-dd79bebe4b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Настройка дистрибуции'])[1]/following::a[1]</value>
      <webElementGuid>27d01de5-0629-4249-b111-a57c20019b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Пропустить'])[1]/preceding::a[1]</value>
      <webElementGuid>ccfff925-5988-47f2-b0d7-2d31b69e5ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[2]</value>
      <webElementGuid>243bcf8e-ea4b-46df-b491-a79cefaab340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Настроить']/parent::*</value>
      <webElementGuid>20535eb7-7697-42e6-ab5c-2512ffe804af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/w/podcast/21380/settings/distribution')]</value>
      <webElementGuid>b871448e-3c8e-43d8-b22e-4042d670c767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>8867f5d6-3dab-4c0e-8636-8b78b5b70396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/w/podcast/21380/settings/distribution' and (text() = 'Настроить' or . = 'Настроить')]</value>
      <webElementGuid>3a96156f-7650-4dbd-b1a8-06535dc49cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
