<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Номер сезона</name>
   <tag></tag>
   <elementGuidId>56dcb6de-3b4b-49a7-abd5-b55eb399d62e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#seasonNum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='seasonNum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed399808-0512-4ecd-a8a8-a90fca25b6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a379fa14-5350-43fa-87cb-4734106693ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>seasonNum</value>
      <webElementGuid>d7c75691-dd76-40ed-b09f-776d33dc48d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>seasonNum</value>
      <webElementGuid>1ae855ea-7201-44cd-8853-9b822fba8663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48258434-79f7-4a18-881d-c6a70ca84203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>c9b5c1c6-25e6-4f2a-ad6a-775b3dd6626a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input css-a1c9b9</value>
      <webElementGuid>5521ea69-c2bf-45ff-afd8-eaa02a1f9b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seasonNum&quot;)</value>
      <webElementGuid>d074d197-8411-4cd7-bf5a-11f53a6608cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='seasonNum']</value>
      <webElementGuid>8091dc00-938c-4f36-a458-e7d836da2a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[2]/div[3]/form/div/div/div/div[9]/div/div/input</value>
      <webElementGuid>dd10b55a-035d-48cc-9a5b-ff3d3f3e80ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>f9a87b45-1837-4302-90e7-cae41ec5513f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'seasonNum' and @name = 'seasonNum' and @type = 'text']</value>
      <webElementGuid>51b927ea-2a45-4360-8eba-612050996b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
