<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Номер эпизода</name>
   <tag></tag>
   <elementGuidId>ce4d2e79-c781-4772-a451-d116f6708bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#releaseNum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='releaseNum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c42a8ec6-b661-45b4-aa54-2d9943480124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0ea756ea-bb0c-4ee1-93c3-1921bb07d348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>releaseNum</value>
      <webElementGuid>a37e3ce0-3f72-4787-ae10-c50318e61ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>releaseNum</value>
      <webElementGuid>94fc56b6-e85f-415b-82cb-caaf499a83c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15dd82fd-fdd7-4148-b3c2-270f4025e46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b607f027-33d7-4ed8-93ba-d030d0444e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input css-a1c9b9</value>
      <webElementGuid>134a12a4-eae6-4b0b-81f5-28ae6e4b9c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;releaseNum&quot;)</value>
      <webElementGuid>1379855c-3a42-4b9b-8ec1-3ae82d076db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='releaseNum']</value>
      <webElementGuid>d6b72810-58d6-4652-9647-76ed0550d637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[2]/div[3]/form/div/div/div/div[9]/div[2]/div/input</value>
      <webElementGuid>41fa959b-0fbc-4bc7-b430-e545d191e296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>8a498638-78fb-4b7f-9779-d3b1e06067ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'releaseNum' and @name = 'releaseNum' and @type = 'text']</value>
      <webElementGuid>27f8de6b-ea6c-4160-aa70-690498ad3752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
