<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Опубликовать позже</name>
   <tag></tag>
   <elementGuidId>f257cfa7-bed5-4f70-986b-399af9988ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.MuiOutlinedInput-input.MuiInputBase-input.MuiInputBase-inputAdornedEnd.css-8z64ca</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Опубликовать сейчас' and @type = 'tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6aca5b00-4829-4c66-946f-1c4a25309319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5f62d9e-6eb3-44fa-a71b-bd0223fdf60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Опубликовать сейчас</value>
      <webElementGuid>c58256f5-c9aa-4a75-9f4f-0b83bd813b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>9417c038-ac62-4fd0-8ba5-d0d74fd6e14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd css-8z64ca</value>
      <webElementGuid>4aa67c47-797c-4b26-889b-17467fc29297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-y0mund-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-a1abyh-Main-root&quot;]/div[@class=&quot;MuiBox-root css-uz4xfq-Main-Content-root&quot;]/div[@class=&quot;MuiBox-root css-1ehfqw6&quot;]/form[1]/div[@class=&quot;MuiBox-root css-1ws491f&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-ra15ob&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root css-i44wyl&quot;]/div[@class=&quot;MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-adornedEnd css-19njklg&quot;]/input[@class=&quot;MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd css-8z64ca&quot;]</value>
      <webElementGuid>d2de1e65-baa3-486d-8d4a-2e1db990a947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[5]</value>
      <webElementGuid>5e050ee2-3ebf-4e19-8273-8e4afa441abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[2]/div[3]/form/div/div/div/div[14]/div/input</value>
      <webElementGuid>7927f996-6663-4cd9-bd98-d38905b15e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/input</value>
      <webElementGuid>b120bea6-48e7-4833-9658-10662a2e6d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Опубликовать сейчас' and @type = 'tel']</value>
      <webElementGuid>fb35de38-5916-4688-a54a-7653e973ad22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
