<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Имя подкаста</name>
   <tag></tag>
   <elementGuidId>b50b7776-9498-484f-92fb-1e695cfe056a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.MuiTypography-root.MuiTypography-p1.css-1kjflzr-Podcast-InfoBlock-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c0b868d9-a0e9-4944-8bfd-b515a869a8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-p1 css-1kjflzr-Podcast-InfoBlock-heading</value>
      <webElementGuid>0a5b4982-b7df-4a9e-9dab-cb0e36b480bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>autotest</value>
      <webElementGuid>706c0fae-9f6f-44f7-bde7-0bb9d161e681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-n2uxri-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-6rvsfg-Main-root&quot;]/div[@class=&quot;MuiBox-root css-zmnw5a-Main-gradient&quot;]/div[@class=&quot;MuiBox-root css-79elbk&quot;]/div[@class=&quot;MuiBox-root css-a91i4s-Main-Content-root&quot;]/div[@class=&quot;MuiBox-root css-1sdgq76-Podcast-InfoBlock-root&quot;]/div[@class=&quot;css-vpup35-Podcast-InfoBlock-content&quot;]/div[@class=&quot;css-zmv2sl-Podcast-InfoBlock-headingWrap&quot;]/h1[@class=&quot;MuiTypography-root MuiTypography-p1 css-1kjflzr-Podcast-InfoBlock-heading&quot;]</value>
      <webElementGuid>c6108e0c-0c1d-487b-ad9b-3da904fde5b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/div/div[3]/div/h1</value>
      <webElementGuid>79467f2e-9819-4ee0-8cef-e6c763ffd3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cвязаться со мной'])[1]/following::h1[1]</value>
      <webElementGuid>0f8952ed-ae01-4c89-b2c6-ad969844ba18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='timur'])[1]/preceding::h1[1]</value>
      <webElementGuid>591e1f81-8f05-4daa-bb70-71bbc7d9cb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='autotest']/parent::*</value>
      <webElementGuid>52918a90-2bef-4552-949d-3f0d58d230cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>215c9c69-e10c-4789-b512-b8838ad99b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'autotest' or . = 'autotest')]</value>
      <webElementGuid>2673fcae-3f11-44c1-a9a0-6594f7bdface</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
