<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Обложка подкаста</name>
   <tag></tag>
   <elementGuidId>53ef3f7c-d2ab-4b2a-96df-becdcb868295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt = 'обложка подкаста']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f3cfb66d-0ba5-4bb9-8840-6b9951795cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>обложка подкаста</value>
      <webElementGuid>ea3342c8-d612-473f-b08b-fa0db9b2cc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://st.zvq.me/r/e2cbada4-99a2-4cde-86f9-0c94473b8e83/poster.jpeg?size=335&amp;1684302730436</value>
      <webElementGuid>bd400755-d6ea-442a-a2a8-c4ddf79de1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>dc720864-a7fb-4a5b-a5da-f7332366f7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>e94111c3-45ff-4e83-93b3-4bb8ff177d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-almznq-Image-root</value>
      <webElementGuid>5cbfb810-2b33-4f61-b0dc-9542bb7a630c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-n2uxri-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-6rvsfg-Main-root&quot;]/div[@class=&quot;MuiBox-root css-zmnw5a-Main-gradient&quot;]/div[@class=&quot;MuiBox-root css-79elbk&quot;]/div[@class=&quot;MuiBox-root css-a91i4s-Main-Content-root&quot;]/div[@class=&quot;MuiBox-root css-1sdgq76-Podcast-InfoBlock-root&quot;]/div[@class=&quot;MuiBox-root css-12cav-Podcast-InfoBlock-coverWrapper&quot;]/span[1]/img[@class=&quot;css-almznq-Image-root&quot;]</value>
      <webElementGuid>eaab4f06-48c8-4f99-83d7-04ee43849c00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/div/div/span/img</value>
      <webElementGuid>263e566f-a7aa-4313-96d2-fa63a2fcd950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='обложка подкаста']</value>
      <webElementGuid>76276ab1-13fc-4ef2-8529-556b0e1b510c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span/img</value>
      <webElementGuid>dbb97db2-1f28-4bfb-a587-3bec2a7a7a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'обложка подкаста' and @src = 'https://st.zvq.me/r/e2cbada4-99a2-4cde-86f9-0c94473b8e83/poster.jpeg?size=335&amp;1684302730436']</value>
      <webElementGuid>39104ba6-9926-40ae-8042-693d7752f6ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
