<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Параграф</name>
   <tag></tag>
   <elementGuidId>36d2737e-b2be-4509-893f-28475b5e771a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.MuiTypography-p1.css-1199qef-Podcast-InfoBlock-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>be3d36a7-5f17-4b1b-acfe-d995f0b541d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-p1 css-1199qef-Podcast-InfoBlock-info</value>
      <webElementGuid>67bfbea9-7a7e-4654-8fb4-c07c6059fe17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Автор: timurКатегория: Бизнес: Инвестиции</value>
      <webElementGuid>618f5286-5fe1-41b8-b839-bb9fe3f26d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-n2uxri-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-6rvsfg-Main-root&quot;]/div[@class=&quot;MuiBox-root css-zmnw5a-Main-gradient&quot;]/div[@class=&quot;MuiBox-root css-79elbk&quot;]/div[@class=&quot;MuiBox-root css-a91i4s-Main-Content-root&quot;]/div[@class=&quot;MuiBox-root css-1sdgq76-Podcast-InfoBlock-root&quot;]/div[@class=&quot;css-vpup35-Podcast-InfoBlock-content&quot;]/div[@class=&quot;css-zmv2sl-Podcast-InfoBlock-headingWrap&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-p1 css-1199qef-Podcast-InfoBlock-info&quot;]</value>
      <webElementGuid>c76bf1e7-7913-45ba-bf6e-60eda8aab74c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/div/div[3]/div/p</value>
      <webElementGuid>dd3ee264-3fd6-460d-b9f7-b3343ea1ace9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='autotest'])[1]/following::p[1]</value>
      <webElementGuid>4c7b4157-f275-47ce-b3d9-c3f90ee5ef30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cвязаться со мной'])[1]/following::p[1]</value>
      <webElementGuid>bc3cf885-097c-4ad7-8270-e5e6ede7094c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Автор:']/parent::*</value>
      <webElementGuid>7e7954cd-79e0-4045-906c-4d8f1b217851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>1c57ec40-991e-4aa2-8ef0-b56892c83ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Автор: timurКатегория: Бизнес: Инвестиции' or . = 'Автор: timurКатегория: Бизнес: Инвестиции')]</value>
      <webElementGuid>e2447e21-f9ee-4a7a-912b-e737308887f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
