<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Параграф</name>
   <tag></tag>
   <elementGuidId>36d2737e-b2be-4509-893f-28475b5e771a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.MuiTypography-p1.css-1199qef-Podcast-InfoBlock-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dc858763-95a2-4c7b-b347-d7550b03045d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-p1 css-1199qef-Podcast-InfoBlock-info</value>
      <webElementGuid>f49ef79c-8e19-42e0-9e42-6fbf9f0cbc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Автор: timurКатегория: Бизнес: Инвестиции</value>
      <webElementGuid>6794034a-317c-4391-ad2f-1b90bd9cba41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-n2uxri-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-6rvsfg-Main-root&quot;]/div[@class=&quot;MuiBox-root css-zmnw5a-Main-gradient&quot;]/div[@class=&quot;MuiBox-root css-79elbk&quot;]/div[@class=&quot;MuiBox-root css-a91i4s-Main-Content-root&quot;]/div[@class=&quot;MuiBox-root css-1sdgq76-Podcast-InfoBlock-root&quot;]/div[@class=&quot;css-vpup35-Podcast-InfoBlock-content&quot;]/div[@class=&quot;css-zmv2sl-Podcast-InfoBlock-headingWrap&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-p1 css-1199qef-Podcast-InfoBlock-info&quot;]</value>
      <webElementGuid>69512c29-1b64-4988-bf8f-2bc514cfc7a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/div/div[3]/div/p</value>
      <webElementGuid>b8e979d9-bd00-48a3-bd15-949d7d45162e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='autotest'])[1]/following::p[1]</value>
      <webElementGuid>7e3bd99c-4df6-438c-ac5d-f45e0424eb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cвязаться со мной'])[1]/following::p[1]</value>
      <webElementGuid>248fdb73-8ddb-497e-9ab6-c187187c450d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Автор:']/parent::*</value>
      <webElementGuid>cd5faad2-0c4b-4cd7-a3d8-8576005bc0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>87bfd66a-375b-4920-a3a7-f5742cf787e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Автор: timurКатегория: Бизнес: Инвестиции' or . = 'Автор: timurКатегория: Бизнес: Инвестиции')]</value>
      <webElementGuid>2c4b2dbd-14ce-4295-9e76-b41d1e543292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
