<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Списокэпизодов</name>
   <tag></tag>
   <elementGuidId>05404cf5-9c92-4165-98ea-40c92b94fab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div/div/div[2]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3fdf016-e63c-4608-81a4-442fc5550099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-172av7n-Episodes-EpisodeListItem-root</value>
      <webElementGuid>220ae4c6-b40d-464f-b8e2-8b3c764cc00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2test223 мая 202303:01</value>
      <webElementGuid>139790be-d365-442d-b78d-ca25467eeaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-n2uxri-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-6rvsfg-Main-root&quot;]/div[@class=&quot;MuiBox-root css-zmnw5a-Main-gradient&quot;]/div[@class=&quot;MuiBox-root css-79elbk&quot;]/div[@class=&quot;MuiBox-root css-a91i4s-Main-Content-root&quot;]/div[@class=&quot;css-yw8f5b&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;css-f1ry9y-Episodes-EpisodeList-itemsWrapper&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;css-172av7n-Episodes-EpisodeListItem-root&quot;]</value>
      <webElementGuid>7ec2728d-0f57-4aca-a9f9-ada0ae883365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>bb056ef1-35aa-4262-8111-d8ecb4f1fd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сезон 1'])[1]/following::div[2]</value>
      <webElementGuid>592f1e12-0d3c-426d-a0b7-5ee4c441bc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[4]</value>
      <webElementGuid>4736e05c-b2a0-47d2-8e20-1b3d53698fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Тимур'])[1]/preceding::div[9]</value>
      <webElementGuid>0a37f091-44b8-43ad-a2a1-662aee6e228a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>eb57258a-b4e2-4bcf-b9fa-4e37fb2d69af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2test223 мая 202303:01' or . = '2test223 мая 202303:01')]</value>
      <webElementGuid>20eb2ee6-23f5-4ee0-8b72-156a69e0f783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
