<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Созданый подкаст из списка</name>
   <tag></tag>
   <elementGuidId>08e8635c-10ba-4d04-8994-427457f433fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1icuz8e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/li/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'lnfzl7nxvd' or . = 'lnfzl7nxvd')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2be91ee4-05f5-486e-8fc8-ab3f1ccb0753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1icuz8e</value>
      <webElementGuid>0adcc4ec-b5d6-4561-a038-f99320cdb9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>lnfzl7nxvd</value>
      <webElementGuid>f833364c-b9a2-4dfa-a2c2-7f697804b2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiModal-root MuiPopover-root css-15dayu0-Containers-PodcastMenu-menu&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiMenu-paper MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiPopover-paper css-i9tkxc&quot;]/ul[@class=&quot;MuiList-root MuiList-padding MuiMenu-list css-r8u8y9&quot;]/div[@class=&quot;MuiBox-root css-1wdr5z8-Podcasts-PodcastList-buttonWrapper&quot;]/li[@class=&quot;MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-b9mo4r-MenuItem-Podcasts-PodcastList-item&quot;]/div[@class=&quot;css-1icuz8e&quot;]</value>
      <webElementGuid>ecab8a7c-b7fc-4c14-9399-48ef57133591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Почта для связи со службой поддержки - support@zvuk.com'])[1]/following::div[14]</value>
      <webElementGuid>27e40f2c-83e4-453b-b1ac-96ef09416852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Оферта на предоставление простой (неисключительной) лицензии'])[1]/following::div[14]</value>
      <webElementGuid>a5692064-8fa3-4355-bf16-5b123bbaaeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Посмотреть все'])[1]/preceding::div[2]</value>
      <webElementGuid>74e5a926-dbb5-4444-8751-4d31f1a437d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Создать новый'])[1]/preceding::div[3]</value>
      <webElementGuid>87065011-0a9b-4248-8e44-9fca7c7d10c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li/div</value>
      <webElementGuid>96c89364-5511-4e3d-bcf5-b248e78290bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'lnfzl7nxvd' or . = 'lnfzl7nxvd')]</value>
      <webElementGuid>9ca020f7-527a-42a7-9bad-390c79e4d373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
