<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Управление подкастами</name>
   <tag></tag>
   <elementGuidId>a8531a23-098f-44dd-a6a8-6acadc30c875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#podcasts-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='podcasts-menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9a38e13-7e7a-40c7-8ab8-cd2e02367392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>podcasts-menu</value>
      <webElementGuid>e4b13a58-2822-4aaa-9510-e8399a460265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1dj97nu-Containers-PodcastMenu-anchor</value>
      <webElementGuid>4a03ee46-ccc7-4fc4-89f1-153b3fa52409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Управление подкастами</value>
      <webElementGuid>74de73a9-faed-42d2-87cb-cefe059b5950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;podcasts-menu&quot;)</value>
      <webElementGuid>5354b377-3d72-4183-a178-b99f47f0075f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='podcasts-menu']</value>
      <webElementGuid>4025c8a6-6191-437d-8057-5678ae481428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/header/div/div/div</value>
      <webElementGuid>e3d2dfad-679c-42e6-b98a-43331c895df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Темная тема'])[1]/following::div[5]</value>
      <webElementGuid>3acfa0cf-8499-4e66-9a78-79255dc5f05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='База знаний'])[1]/following::div[6]</value>
      <webElementGuid>a1a816d7-9e4b-43ec-9511-ed5e45962901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div</value>
      <webElementGuid>96020963-e9d5-4854-81d6-8d12abe2ea92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'podcasts-menu' and (text() = 'Управление подкастами' or . = 'Управление подкастами')]</value>
      <webElementGuid>d6a8f80b-13d8-48f1-b80e-07c007b7f166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
