<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Черновик</name>
   <tag></tag>
   <elementGuidId>a2b1c859-fb89-4a63-9be5-01f57fc11c6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-uz4xfq-Main-Content-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text() = 'Черновик'] </value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12395e10-dbe1-4bef-b6a8-15c5c23b20e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-uz4xfq-Main-Content-root</value>
      <webElementGuid>8e098db3-efcc-4fd6-b490-f977aea74144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Все эпизоды​​Фильтр​​Сначала новые​​​​Сначала новые​​Сезон 1Названиеepisode#1Прослушивания0Дата создания04.05.23 - 18:08mp300:003.1kbТипПолныйСтатусОпубликованБез сезонаНазвание-#-Прослушивания0Дата создания04.05.23 - 18:35mp300:000bТипПолныйСтатусЧерновикНазвание-#-Прослушивания0Дата создания04.05.23 - 18:18mp300:000bТипПолныйСтатусЧерновик1</value>
      <webElementGuid>0e6b00c7-d20c-4e86-be0f-278dbcda7ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-y0mund-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-jt84w5-Main-root&quot;]/div[@class=&quot;MuiBox-root css-uz4xfq-Main-Content-root&quot;]</value>
      <webElementGuid>250b5e6d-55bc-4fa9-970e-12190baaa3b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[2]</value>
      <webElementGuid>364fc969-6c12-476b-bc3e-1c13b131f5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить эпизод'])[1]/following::div[4]</value>
      <webElementGuid>34b8cc2c-47b4-400f-8ffa-f2dac0d4c86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test322'])[1]/following::div[6]</value>
      <webElementGuid>bd4e17bc-0989-43bd-a904-6fb32c9c372c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]</value>
      <webElementGuid>22aecf7d-79d2-4c28-b1ed-56b4173a5fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Все эпизоды​​Фильтр​​Сначала новые​​​​Сначала новые​​Сезон 1Названиеepisode#1Прослушивания0Дата создания04.05.23 - 18:08mp300:003.1kbТипПолныйСтатусОпубликованБез сезонаНазвание-#-Прослушивания0Дата создания04.05.23 - 18:35mp300:000bТипПолныйСтатусЧерновикНазвание-#-Прослушивания0Дата создания04.05.23 - 18:18mp300:000bТипПолныйСтатусЧерновик1' or . = 'Все эпизоды​​Фильтр​​Сначала новые​​​​Сначала новые​​Сезон 1Названиеepisode#1Прослушивания0Дата создания04.05.23 - 18:08mp300:003.1kbТипПолныйСтатусОпубликованБез сезонаНазвание-#-Прослушивания0Дата создания04.05.23 - 18:35mp300:000bТипПолныйСтатусЧерновикНазвание-#-Прослушивания0Дата создания04.05.23 - 18:18mp300:000bТипПолныйСтатусЧерновик1')]</value>
      <webElementGuid>e14651c5-7887-4b92-83f9-b03a3a1e0ed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
