<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Главная</name>
   <tag></tag>
   <elementGuidId>9e2b9385-9c69-41ed-9514-fbb494ed85dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiListItemButton-root.MuiListItemButton-gutters.MuiButtonBase-root.Mui-active.css-14cge7l-SidebarListItem-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@role = 'button' and (text() = 'Главная' or . = 'Главная')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>811be0a4-f1b1-4c3f-8bbd-81cf8aa114c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root Mui-active css-14cge7l-SidebarListItem-root</value>
      <webElementGuid>ed771328-1eff-44fa-b829-62624b3374c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>65dd9747-d83c-4a38-8ab9-b9c224341a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7294893b-7ab0-4351-bd32-2d25ae08fd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Главная</value>
      <webElementGuid>bbfc6dfb-f3b6-4ebf-8e2a-05cbcf929c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-y0mund-Layout-root&quot;]/nav[@class=&quot;css-1eu2wq9-Sidebar-root&quot;]/div[@class=&quot;css-tyints-Sidebar-menu&quot;]/ul[@class=&quot;MuiList-root MuiList-padding css-nvdwdx-SidebarList-root&quot;]/li[1]/a[@class=&quot;MuiTypography-root MuiTypography-p4 MuiLink-root MuiLink-underlineNone css-d6d3zt&quot;]/div[@class=&quot;MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root Mui-active css-14cge7l-SidebarListItem-root&quot;]</value>
      <webElementGuid>75cbce96-df7b-423d-9266-91c74b7b9d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/nav/div[2]/ul/li/a/div</value>
      <webElementGuid>d2312cb6-d1b8-4abf-a2a4-3edd107e75cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Аналитика'])[1]/preceding::div[4]</value>
      <webElementGuid>61c07163-a90f-44dd-93be-48485b829035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>ab34b185-3541-4664-a2f8-65cc3abe1b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Главная' or . = 'Главная')]</value>
      <webElementGuid>cba8c7ed-f85d-45d2-96f9-45ba804e72a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
