<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Настройка подкаста</name>
   <tag></tag>
   <elementGuidId>55993385-4214-46db-bfc8-10eca6f8f166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@role = 'button' and (text() = 'Настройки подкаста' or . = 'Настройки подкаста')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11257a92-3423-4abb-9974-3e623e931f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root  css-14cge7l-SidebarListItem-root</value>
      <webElementGuid>1f179d4e-2f12-4388-97ce-43786e18fbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c8e56553-f7f4-4429-b29c-7bdd88f62791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd56f539-69c5-441e-ba40-5e7b59a9fa7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Настройки подкаста</value>
      <webElementGuid>37497015-4d53-46fb-a489-abb060f61211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-y0mund-Layout-root&quot;]/nav[@class=&quot;css-1eu2wq9-Sidebar-root&quot;]/div[@class=&quot;css-tyints-Sidebar-menu&quot;]/ul[@class=&quot;MuiList-root MuiList-padding css-nvdwdx-SidebarList-root&quot;]/li[3]/a[@class=&quot;MuiTypography-root MuiTypography-p4 MuiLink-root MuiLink-underlineNone css-d6d3zt&quot;]/div[@class=&quot;MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root  css-14cge7l-SidebarListItem-root&quot;]</value>
      <webElementGuid>86ac0290-aa83-4ffa-a036-315dab89d2e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/nav/div[2]/ul/li[3]/a/div</value>
      <webElementGuid>c825b788-ce0b-4115-b3ad-7544e84f327a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Аналитика'])[1]/following::div[1]</value>
      <webElementGuid>d5289fca-d161-416a-af49-675c2d23e2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Главная'])[2]/following::div[4]</value>
      <webElementGuid>a1cf830e-3753-4dd7-b6da-1dc0122cb9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Эпизоды'])[1]/preceding::div[4]</value>
      <webElementGuid>9dce1d27-a333-4052-86ed-c01335de7946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div</value>
      <webElementGuid>ef6a9f07-6ea3-44d2-9b8d-dd8960112d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Настройки подкаста' or . = 'Настройки подкаста')]</value>
      <webElementGuid>000b7d30-4c15-45b7-9319-b059df73b031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
