<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Переключение темы</name>
   <tag></tag>
   <elementGuidId>311f42af-17fc-4f67-926b-c4863cc7baa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;darkTheme&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='darkTheme']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c19dae4-ca1d-45ca-98a7-076aff3574f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSwitch-input PrivateSwitchBase-input css-1m9pwf3</value>
      <webElementGuid>34172407-97f2-415a-a7cb-7517cc921f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>darkTheme</value>
      <webElementGuid>7c8413a8-5cdf-41f6-bdcb-b7b66323c538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9e711dae-70d9-4345-afae-5935f0f9768e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>theme_checker</value>
      <webElementGuid>83a38069-f80f-49f7-96a9-0149220023dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-y0mund-Layout-root&quot;]/nav[@class=&quot;css-1eu2wq9-Sidebar-root&quot;]/div[@class=&quot;css-tyints-Sidebar-menu&quot;]/ul[@class=&quot;MuiList-root MuiList-padding css-1yv57ta-SidebarList-root&quot;]/li[1]/div[@class=&quot;css-1qzusr4&quot;]/span[@class=&quot;MuiSwitch-root MuiSwitch-sizeMedium css-11ko75r&quot;]/span[@class=&quot;MuiSwitch-switchBase MuiSwitch-colorPrimary Mui-checked MuiButtonBase-root MuiSwitch-switchBase MuiSwitch-colorPrimary Mui-checked PrivateSwitchBase-root Mui-checked css-3gtz8b&quot;]/input[@class=&quot;MuiSwitch-input PrivateSwitchBase-input css-1m9pwf3&quot;]</value>
      <webElementGuid>e0057cb6-4582-4d70-9dc3-e0f67f4eec47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='darkTheme']</value>
      <webElementGuid>14305b98-5647-4483-ab43-1c11f3f6ee04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/nav/div[2]/ul[3]/li/div/span/span/input</value>
      <webElementGuid>60d9c90b-1e8c-401c-a533-76bb7202f1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d5821bb6-2319-4a5c-9264-21d4666df92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'darkTheme' and @type = 'checkbox']</value>
      <webElementGuid>b76443bd-7f82-4455-9c89-780c0286b85e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
