<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Профиль</name>
   <tag></tag>
   <elementGuidId>02202709-6db0-4517-8e1e-0f3115b44d0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Профиль')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.MuiButton-root.MuiButton-outlined.MuiButton-outlinedPrimary.MuiButton-sizeLarge.MuiButton-outlinedSizeLarge.MuiButton-disableElevation.MuiButtonBase-root.css-b2bmev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94b0839a-1724-48d8-a35f-c3189d2af302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeLarge MuiButton-outlinedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-b2bmev</value>
      <webElementGuid>8eb7b135-151c-4266-8a1a-4251ec4dfb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20b4f374-52f0-4019-a0b2-614290eed3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/w/sign-in</value>
      <webElementGuid>21045526-f41a-40bf-99e5-b051bd3697f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Вход</value>
      <webElementGuid>3e64057a-eb96-44ae-98c8-649cde278a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/div[@class=&quot;MuiBox-root css-y173z4-Landing-root&quot;]/header[@class=&quot;MuiBox-root css-r6qb13-LandingHeader-root&quot;]/div[@class=&quot;MuiBox-root css-69i1ev&quot;]/header[@class=&quot;css-1qgvkyg-Header-root-LandingHeader-header&quot;]/div[@class=&quot;MuiBox-root css-zdpt2t&quot;]/a[@class=&quot;MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary MuiButton-sizeLarge MuiButton-outlinedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-b2bmev&quot;]</value>
      <webElementGuid>f9fb92d6-bc32-4d8b-9d82-ffece3b6af68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/header/div/header/div/a</value>
      <webElementGuid>ad5eadc9-ba99-453e-b425-8a8d9583916b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Вход')]</value>
      <webElementGuid>1bc08d67-f5a8-45fd-bac5-98ea12b21ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Бета версия'])[1]/following::a[1]</value>
      <webElementGuid>95486dd5-8e6a-4635-a54d-472d7c9b1d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Студио для подкастеров'])[2]/preceding::a[1]</value>
      <webElementGuid>458a9076-606e-4868-935a-4836d777d74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Рассказывайте истории — мы позаботимся, чтобы они были всегда доступны и нашли свою аудиторию'])[1]/preceding::a[1]</value>
      <webElementGuid>6da20236-a08b-47c9-951f-ba5564ac6ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Вход']/parent::*</value>
      <webElementGuid>e294d615-da9a-4862-b25a-daad66c02e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/w/sign-in')]</value>
      <webElementGuid>897be350-db62-46a2-8220-68c87509cbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>46aa8dd9-e0a4-4471-a0df-e8d9cbe1fe88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/w/sign-in' and (text() = 'Вход' or . = 'Вход')]</value>
      <webElementGuid>e8d9fb0a-2295-4bd7-97b7-674a66143b0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
