<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Вход</name>
   <tag></tag>
   <elementGuidId>92331404-578c-4db9-a95f-8e29c13d4b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[(text() = 'Вход' or . = 'Вход')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.MuiTypography-root.MuiTypography-h4.MuiTypography-alignCenter.MuiTypography-gutterBottom.css-1pur40g</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c8a62d76-45b2-4b8a-bbaf-a7af712dcba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h4 MuiTypography-alignCenter MuiTypography-gutterBottom css-1pur40g</value>
      <webElementGuid>0d74e45b-10be-47ef-a5ef-23480563a7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Вход</value>
      <webElementGuid>7975b3b3-cb57-415d-bc6a-09b3246bf0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;jss1 jss2&quot;]/main[@class=&quot;MuiBox-root css-3umasb-Main-root-Auth-Main-root&quot;]/div[@class=&quot;Ui-Container-withPadding MuiBox-root css-mrz6wc-Ui-Container-root&quot;]/div[@class=&quot;css-a2qr2c-Ui-Container-inner&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded css-1nvm7uz-Auth-Main-paper&quot;]/form[1]/h1[@class=&quot;MuiTypography-root MuiTypography-h4 MuiTypography-alignCenter MuiTypography-gutterBottom css-1pur40g&quot;]</value>
      <webElementGuid>a9899947-902d-46ce-82dc-34b821119af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div/form/h1</value>
      <webElementGuid>ff623bb4-dd08-4d48-8ef8-5fcc88bb11dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>802dd0be-fbc2-4ff5-bc03-689461c39574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Вход' or . = 'Вход')]</value>
      <webElementGuid>c0cc4054-aa81-4e32-8761-24650f7128b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
