<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Зарегистрироваться</name>
   <tag></tag>
   <elementGuidId>9e3ca690-cd09-4179-9896-74bd1b5359a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-disableElevation.MuiButtonBase-root.css-hchuko</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Зарегистрироваться')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>692b9f75-8c8f-4b6c-b267-511c3b199d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-hchuko</value>
      <webElementGuid>887aabb8-4f97-406b-a855-e4c8bbb7b6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63c4cc38-37da-4270-aaf7-b602212a1c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82359315-1f66-4648-976e-efe85838940a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Зарегистрироваться</value>
      <webElementGuid>cb931622-8d86-4044-8013-67298fed81be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/div[@class=&quot;MuiBox-root css-y173z4-Landing-root&quot;]/header[@class=&quot;MuiBox-root css-r6qb13-LandingHeader-root&quot;]/div[@class=&quot;MuiBox-root css-zp8oa2&quot;]/div[@class=&quot;MuiBox-root css-j7qwjs&quot;]/div[@class=&quot;MuiBox-root css-l3qq17&quot;]/a[@class=&quot;MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-hchuko&quot;]</value>
      <webElementGuid>9f54b868-7713-4ef9-8212-5527a9fe24e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/header/div[2]/div[2]/div/a</value>
      <webElementGuid>8b07cd09-9e61-46fc-ae67-eeb32a15af7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Зарегистрироваться')]</value>
      <webElementGuid>722dbb42-35ce-4ffb-ac60-613b3afc1570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Рассказывайте истории — мы позаботимся, чтобы они были всегда доступны и нашли свою аудиторию'])[1]/following::a[1]</value>
      <webElementGuid>4ec02d61-6d0c-4f3e-90d4-7ac983e7792c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Студио для подкастеров'])[2]/following::a[1]</value>
      <webElementGuid>48cc6dab-ab1e-401b-95f2-198377f79c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Вход'])[2]/preceding::a[1]</value>
      <webElementGuid>83084fa3-2cf6-410b-82c1-2b73ea4ea435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Бесплатный и безлимитный хостинг'])[1]/preceding::a[2]</value>
      <webElementGuid>aa7807d9-5f23-448e-92c2-2d3971e0937e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Зарегистрироваться']/parent::*</value>
      <webElementGuid>8f155871-e19b-459b-b105-fb42cbcc43f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>b8c5e5a6-a0ad-4495-8472-8545fcdc868a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Зарегистрироваться' or . = 'Зарегистрироваться')]</value>
      <webElementGuid>dde8f4f7-5418-40b1-aa41-e0a9ad6d36f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
