<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ОшибкаПароля</name>
   <tag></tag>
   <elementGuidId>64e4b18b-4349-4a5e-9c0a-34db4a7674a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='password-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>26e6cbbe-9e51-4cf3-a678-9f152bd8288d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-filled Mui-required css-463v7</value>
      <webElementGuid>3b73457c-02ed-4683-9a75-e817fdcd0be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-helper-text</value>
      <webElementGuid>d8574c35-f06b-4ba0-ab3b-f4bcf3aa6b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Введите корректный пароль</value>
      <webElementGuid>5481fdbe-b767-42c1-ba3a-6099582dace1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-helper-text&quot;)</value>
      <webElementGuid>bfd51dce-5ce4-4fa7-918b-71093c9c5b8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='password-helper-text']</value>
      <webElementGuid>d756df4f-da30-4e94-b2d1-da65022d1700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg']/main/div/div/div/form/div[3]/p</value>
      <webElementGuid>f7375f5a-8537-4b02-a913-ab0b89d015e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Пароль должен содержать:'])[1]/preceding::p[1]</value>
      <webElementGuid>1b34fe32-8f5a-4e72-8be8-accca4f6991a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Введите корректный пароль']/parent::*</value>
      <webElementGuid>0f06b6b4-db70-4043-b328-48c70cb6fd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>3c63b5f1-9a43-49bb-b7ea-67ea82510e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'password-helper-text' and (text() = 'Введите корректный пароль' or . = 'Введите корректный пароль')]</value>
      <webElementGuid>42f742fc-31b2-42a0-b1b2-16a4aeb1ae1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
