<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ОшибкаБезПароля</name>
   <tag></tag>
   <elementGuidId>dcff53ba-89ae-4bf5-8651-8a04141c7ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id = 'password-helper-text' and (text() = 'Введите пароль' or . = 'Введите пароль')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8ffd1d82-582b-42e9-b939-e84a5a58051f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-463v7</value>
      <webElementGuid>0242af29-8fd1-4cc0-ba02-375722b4cca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-helper-text</value>
      <webElementGuid>0b415739-3462-4d41-91b0-c1209b5ad0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Введите пароль</value>
      <webElementGuid>38144109-897b-417e-9d29-4c1f862f66a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-helper-text&quot;)</value>
      <webElementGuid>8711a95b-cfc1-4097-ba8d-a54fcb74dae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='password-helper-text']</value>
      <webElementGuid>8151eb74-f4b9-4fad-aa13-f0315698e4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg']/main/div/div/div/form/div[3]/p</value>
      <webElementGuid>107eeda1-eac1-4c85-9a5b-1d31e6e9aeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Пароль должен содержать:'])[1]/preceding::p[1]</value>
      <webElementGuid>007639c3-8267-4a8d-a354-e915d5a2d350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Введите пароль']/parent::*</value>
      <webElementGuid>cf7f295a-dd4a-46d1-8601-fe9cd617f112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>36569e10-4dff-454c-9b71-b7450eb39df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'password-helper-text' and (text() = 'Введите пароль' or . = 'Введите пароль')]</value>
      <webElementGuid>1020eeed-1947-4199-ba94-c32d4611a7c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
