<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ОшибкаИмени</name>
   <tag></tag>
   <elementGuidId>fc60b52d-cb82-4313-b723-7720d3bf9f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id = 'name-helper-text' and (text() = 'Имя не может содержать менее 2 и более 200 символов' or . = 'Имя не может содержать менее 2 и более 200 символов')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>856a134b-6c64-48aa-b651-1a448f20b916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-filled Mui-required css-463v7</value>
      <webElementGuid>f6849350-d250-48f1-a3a2-8615c138da47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-helper-text</value>
      <webElementGuid>7854751c-d178-44b7-80c2-481bd217f0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Имя не может содержать менее 2 и более 200 символов</value>
      <webElementGuid>f0de012c-60ac-447e-93d9-9c599e784540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-helper-text&quot;)</value>
      <webElementGuid>9aafbcb2-8895-4573-86b7-3ceea0110e66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='name-helper-text']</value>
      <webElementGuid>acac1350-8c2e-4858-b63f-2729d3f51c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg']/main/div/div/div/form/div[2]/p</value>
      <webElementGuid>ee78bed9-58a9-4d0a-84a1-3a5ac33cd24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Имя не может содержать менее 2 и более 200 символов']/parent::*</value>
      <webElementGuid>7ab63d8e-da73-42c7-b80b-bb106639bb30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/p</value>
      <webElementGuid>92bc4c92-8e6d-4fc5-a9b2-c41236f80350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'name-helper-text' and (text() = 'Имя не может содержать менее 2 и более 200 символов' or . = 'Имя не может содержать менее 2 и более 200 символов')]</value>
      <webElementGuid>41525bcb-2f5d-4691-8913-ddab91fe8fb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
