<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ОшибкаБезИмени</name>
   <tag></tag>
   <elementGuidId>c91788f6-d75b-4735-a039-6d5810c60ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id = 'name-helper-text' and (text() = 'Введите имя' or . = 'Введите имя')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d070fe97-8648-4b6d-a6d2-8f6d16f8395f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium Mui-required css-463v7</value>
      <webElementGuid>3fece4c5-4c5f-4940-8e6a-380885e46365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-helper-text</value>
      <webElementGuid>ba056838-514d-40d0-9250-d0239cc3f3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Введите имя</value>
      <webElementGuid>3c8580d7-c07c-442d-8efd-5c9176030783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-helper-text&quot;)</value>
      <webElementGuid>54db6e0d-c72b-49b1-b07b-17cd25b44fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='name-helper-text']</value>
      <webElementGuid>d54215dd-f0fb-4a94-8c03-857fa07fb7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg']/main/div/div/div/form/div[2]/p</value>
      <webElementGuid>0e48b399-dd66-496c-b0df-820f6c21fc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Введите имя']/parent::*</value>
      <webElementGuid>609e6660-4870-4f59-bba1-8fc6c63f91e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/p</value>
      <webElementGuid>8fa19f2a-d869-4a95-95cd-1c66c534fa0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'name-helper-text' and (text() = 'Введите имя' or . = 'Введите имя')]</value>
      <webElementGuid>e2231a28-ced9-41e1-9642-2939109ded8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
