<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ОшибкаПочты</name>
   <tag></tag>
   <elementGuidId>db7adcbd-31db-4dca-8727-f0d76796eed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-helper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id = 'email-helper-text' and (text() = 'Введите корректный email в формате example@mail.ru' or . = 'Введите корректный email в формате example@mail.ru')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f9e51829-a716-4ffe-9e3e-b054fafb428d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-filled Mui-required css-463v7</value>
      <webElementGuid>20f4db6f-20d6-4bce-bf48-3af519a3eaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-helper-text</value>
      <webElementGuid>8502fd1f-2c29-4d63-8539-aa8caa563f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Введите корректный email в формате example@mail.ru</value>
      <webElementGuid>043aeecd-130b-42a5-97e9-1e27957f275e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-helper-text&quot;)</value>
      <webElementGuid>4cbaf968-a841-4da6-9467-93157e6d43fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='email-helper-text']</value>
      <webElementGuid>d9333441-ac43-43f2-a59e-ac2e26a54bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg']/main/div/div/div/form/div/p</value>
      <webElementGuid>4e5b7989-6da7-4487-9b61-80e7c28d700e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Регистрация'])[1]/following::p[2]</value>
      <webElementGuid>3e7b9426-a1fb-4a3b-86c4-142a9bc7b646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Введите корректный email в формате example@mail.ru']/parent::*</value>
      <webElementGuid>56c48bc4-8066-48f2-aff6-7d577852f7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/p</value>
      <webElementGuid>fd0f9e40-d5bf-4806-bdf1-0f8dfa3e9eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'email-helper-text' and (text() = 'Введите корректный email в формате example@mail.ru' or . = 'Введите корректный email в формате example@mail.ru')]</value>
      <webElementGuid>83a453fe-c95d-49af-866b-4dde5d4d9755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
