<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Чекбокс1</name>
   <tag></tag>
   <elementGuidId>31d24a21-8d4e-4a57-9c08-d1209f9221a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#termsAgreement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termsAgreement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c0e31b9-73fe-460c-8725-5d06b5d1f23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input css-1m9pwf3</value>
      <webElementGuid>4ed5ab9c-ce26-4d5c-8f44-1448e11818c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termsAgreement</value>
      <webElementGuid>eda37ad8-568a-464e-9fcb-74b9457f5cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0183653c-ab3a-4118-8f28-59ebacbe9929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d19d82c4-1d0e-43fa-bf62-b3ed16b90269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termsAgreement&quot;)</value>
      <webElementGuid>0c2bd0e1-7f81-4628-bb78-0feae5914291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termsAgreement']</value>
      <webElementGuid>51fa6e5c-bfba-4baa-8de9-a2160dd0a86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg']/main/div/div/div/form/div[6]/label/div/span/input</value>
      <webElementGuid>ca020d4b-7752-4bb5-b0c9-728b83141c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>a51b9358-e6d8-4c7f-9c64-55d8322c525a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termsAgreement' and @type = 'checkbox']</value>
      <webElementGuid>8245ace2-bcb7-4b37-b91b-f391a95a8c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
