<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3d756d81-b80f-40bf-85f9-8ab33c82232f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0df789cb-3714-4e1f-b82f-dfab8a035b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://st.zvooq.ru/r/e2cbada4-99a2-4cde-86f9-0c94473b8e83/poster.jpeg</value>
      <webElementGuid>2cc3803d-889d-4304-8ae8-ae1503b513e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>924</value>
      <webElementGuid>baedcf1a-d0be-46e5-a02e-a0cb0bdeacff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>924</value>
      <webElementGuid>45406b91-7032-454c-831d-8281de01c678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/img[1]</value>
      <webElementGuid>609fd3c6-2c1b-42f0-b012-97ba9ed2a7f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://st.zvooq.ru/r/e2cbada4-99a2-4cde-86f9-0c94473b8e83/poster.jpeg')]</value>
      <webElementGuid>4b87466c-79e8-48ea-9aad-61fba06ce317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3bbc17cf-8a67-483e-8923-f9eefd38a971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://st.zvooq.ru/r/e2cbada4-99a2-4cde-86f9-0c94473b8e83/poster.jpeg']</value>
      <webElementGuid>4b01db3e-a4de-4f26-9e9d-51fdc1f4ef96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
