<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sound</name>
   <tag></tag>
   <elementGuidId>1e275588-719c-4ec6-b1ff-07407728c362</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>video[name=&quot;media&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@name = 'media']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>675eaf63-fadc-4553-8d75-4f7a388df2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>media</value>
      <webElementGuid>4c188ad7-d7cb-41ab-ace3-0f2a9d68b521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/video[1]</value>
      <webElementGuid>bac33d04-929e-4f1c-98ac-3629ad5bc408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@name='media']</value>
      <webElementGuid>28407fd9-e568-40d5-9ed1-dda54270b752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]/body[1]/video[1]'])[1]/preceding::video[1]</value>
      <webElementGuid>25939ef5-2bb7-4615-9944-ef6465a2390b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>d49a4e04-4c0c-4b79-9e9c-5f6441843bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@name = 'media']</value>
      <webElementGuid>9fc71960-ac6c-4b2f-8e2c-8104b18d4ae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
