<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Картинка почты</name>
   <tag></tag>
   <elementGuidId>fbda2219-bfd5-44dd-9f6a-d421ff9b1a43</elementGuidId>
   <imagePath>C:\Users\timur\Katalon Studio\My First Web UI Project\Screenshots\Targets\Page_\Картинка почты.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\timur\Katalon Studio\My First Web UI Project\Screenshots\Targets\Page_\Картинка почты.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>f7d59381-e3c7-4482-a3f8-4dafa0ae8a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M21.629 82.357a9.228 9.228 0 009.228 9.229h58.286a9.228 9.228 0 009.228-9.229V38.643a9.228 9.228 0 00-9.228-9.229H30.857a9.228 9.228 0 00-9.228 9.229v43.714z</value>
      <webElementGuid>b42c0559-5e54-4e2c-a71f-7858bb2b039d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>url(#mail_svg__paint1_linear)</value>
      <webElementGuid>e1d46d89-7457-42a9-afec-3fe2bb399ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#E8EDF8</value>
      <webElementGuid>8c7af940-fabe-44ba-bde4-3eb5863ec455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>8.743</value>
      <webElementGuid>7fd696e3-2d96-4c30-abb0-1302a0740660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-1xprv68-Main-root-Auth-Main-root&quot;]/div[@class=&quot;Ui-Container-withPadding MuiBox-root css-mrz6wc-Ui-Container-root&quot;]/div[@class=&quot;css-a2qr2c-Ui-Container-inner&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded css-e8dape-Auth-Main-paper&quot;]/form[1]/div[@class=&quot;css-1hiaw9w&quot;]/svg[1]/path[2]</value>
      <webElementGuid>3443a324-f9b4-46ea-93eb-ba8872b99d85</webElementGuid>
   </webElementProperties>
</WebElementEntity>
