<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Дистрибуция</name>
   <tag></tag>
   <elementGuidId>b211e9f7-3aa8-437a-8408-d510928f0c5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, 'settings/distribution')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7ae6df7-96f7-41c9-8ae0-81d537f0b682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-12fuyr4</value>
      <webElementGuid>793d8204-c085-4f8b-a1c7-96a189a0505c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>990c0cf1-ee87-44fa-9611-3d60acc828f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b8c35325-ee17-4971-b6c1-30525a2108c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>536d25ef-4b39-4b4f-b697-aa38da0a9551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/w/podcast/21380/settings/distribution</value>
      <webElementGuid>b399ffce-4448-42fa-a052-b42955617642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Дистрибуция</value>
      <webElementGuid>bb89c20f-cbbc-4e87-9363-a571092ad1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-y0mund-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-a1abyh-Main-root&quot;]/div[@class=&quot;MuiBox-root css-byfya-Subheader-root-Podcasts-SettingsTabs-root&quot;]/div[@class=&quot;MuiBox-root css-vt1xa6-Podcasts-SettingsTabs-tabsContainer&quot;]/div[@class=&quot;MuiTabs-root css-51fxvq&quot;]/div[@class=&quot;Podcasts-SettingsTabs-scroller MuiTabs-scroller MuiTabs-hideScrollbar MuiTabs-scrollableX css-1t0s2fz&quot;]/div[@class=&quot;Podcasts-SettingsTabs-scrollableContainer MuiTabs-flexContainer css-7sga7m&quot;]/a[@class=&quot;MuiButtonBase-root MuiTab-root MuiTab-textColorPrimary css-12fuyr4&quot;]</value>
      <webElementGuid>9e6fa308-7104-4ba9-a92a-dc24ed477d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div[2]/div/div[2]/div/a[2]</value>
      <webElementGuid>84ef2da5-831b-4564-a6bd-b4514dea082f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Дистрибуция')]</value>
      <webElementGuid>fda2b8b5-57ef-48b9-9173-bd5dd4ec6400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактирование'])[1]/following::a[1]</value>
      <webElementGuid>dfa64a9c-e88e-486a-ab70-50dfc1cda164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сохранить изменения'])[1]/following::a[2]</value>
      <webElementGuid>8fc807bf-9574-490f-b658-acf82b9c2084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сайт подкаста'])[1]/preceding::a[1]</value>
      <webElementGuid>555f605b-739d-4226-b5a4-536114e1f6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Сохранить изменения'])[2]/preceding::a[2]</value>
      <webElementGuid>de92f740-3878-411b-b986-5c2aa6f241bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Дистрибуция']/parent::*</value>
      <webElementGuid>6eb2c9a3-c9b9-4cb5-b99b-acc8564c76ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/w/podcast/21380/settings/distribution')]</value>
      <webElementGuid>bd5ed728-58b1-4423-8372-338a168f7abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>3341ed04-2ea1-437e-8db4-c4a99ed641ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/w/podcast/21380/settings/distribution' and (text() = 'Дистрибуция' or . = 'Дистрибуция')]</value>
      <webElementGuid>19054c50-ee5f-47a7-9470-b054d7d8e6e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
