<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Аккаунт2</name>
   <tag></tag>
   <elementGuidId>b1326364-759f-4e7d-bf81-51411a9640ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button/div)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-1bpd844-Avatar-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d58f49a0-0aca-4b78-8319-57f85f3a110c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-1bpd844-Avatar-root</value>
      <webElementGuid>670816fd-98d8-4381-98cd-9464e479374e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-y0mund-Layout-root&quot;]/header[@class=&quot;css-89cjwe-Header-root&quot;]/div[@class=&quot;css-1qvs8f0&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;css-1mcox54&quot;]/div[@class=&quot;MuiBox-root css-79elbk&quot;]/div[@class=&quot;MuiBox-root css-1tzeee1&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeSmall css-dspl7f&quot;]/div[@class=&quot;MuiBox-root css-1bpd844-Avatar-root&quot;]</value>
      <webElementGuid>60f82bf3-9776-4987-9e45-df7cd1d70634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/header/div/div[2]/div/div/div/button/div</value>
      <webElementGuid>fca1d8d4-cc1d-4ceb-b89d-80fd52242646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить эпизод'])[1]/following::div[3]</value>
      <webElementGuid>9fd7e265-f413-43ca-bda2-82543d8e23a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Темная тема'])[1]/following::div[11]</value>
      <webElementGuid>30012e48-d2e5-47aa-9616-f9528f12c947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Новое описание'])[1]/preceding::div[3]</value>
      <webElementGuid>88e50f7c-977d-497c-be70-4354fd570e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Развернуть'])[1]/preceding::div[13]</value>
      <webElementGuid>9422b9e2-f193-4a94-8ab1-eb43f7a843c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>e6dd9e48-d384-4f24-908b-e399501fc5fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
