<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Аккаунт1</name>
   <tag></tag>
   <elementGuidId>1fba529a-3df8-4a10-a9e0-a6e0024364a4</elementGuidId>
   <imagePath>Screenshots/Targets/Page_/svg.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Аккаунт' or . = 'Аккаунт') and @type = 'button']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_/svg.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fa6b900-975a-4e39-ba56-b411975a2f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>//*[@class = 'MuiBox-root css-1bpd844-Avatar-root']</value>
      <webElementGuid>05914a06-2732-44ba-ae51-a696f2dfd182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Аккаунт</value>
      <webElementGuid>2d1fe848-7cda-4fb1-b0bb-8b1ba46020a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;css-1pgy6np-UI-MobileMenu-root&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation1 MuiAccordion-root MuiAccordion-gutters css-zr4ohy-UI-MenuAccordion-root&quot;]/div[@class=&quot;MuiButtonBase-root MuiAccordionSummary-root MuiAccordionSummary-gutters css-jfj47m-UI-MenuAccordion-summary&quot;]/div[@class=&quot;MuiAccordionSummary-content MuiAccordionSummary-contentGutters css-17o5nyn&quot;]</value>
      <webElementGuid>e13c03c7-6610-4d2f-9076-be9c25e2df0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb877a78-322b-49bd-a0ec-aa407e8efb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac56b77a-50e7-4461-a165-d952472cf000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Перенести'])[1]/following::div[3]</value>
      <webElementGuid>81794251-4701-42a5-a0e7-632cda325701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Создать новый'])[1]/following::div[3]</value>
      <webElementGuid>21ff50d3-d0a9-4794-9d9a-a4d1a502b5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Профиль'])[1]/preceding::div[4]</value>
      <webElementGuid>5e2ca45b-c6a1-4758-b817-40846e9afcad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div</value>
      <webElementGuid>1d721064-fe9a-406b-9684-5c5f82e9f1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Аккаунт' or . = 'Аккаунт')]</value>
      <webElementGuid>be969163-c340-4776-bb01-17f92fc31fb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
