<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Подтвердить</name>
   <tag></tag>
   <elementGuidId>71587cea-f310-4917-b5b6-eeeabe195705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.MuiTypography-root.MuiTypography-p4.MuiLink-root.MuiLink-underlineNone.MuiLink-button.css-1lfxrpm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Подтвердить' or . = 'Подтвердить')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90a7bfe9-09cb-4bab-a664-10fc3ef0b86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-p4 MuiLink-root MuiLink-underlineNone MuiLink-button css-1lfxrpm</value>
      <webElementGuid>9a5ff4fa-f0e4-4a43-ae35-4acac1d0e946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>be83a106-3720-4c3d-a9a3-b9cf5fe84d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Подтвердить</value>
      <webElementGuid>a3d608e9-ef37-49a1-9229-754285224c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-y0mund-Layout-root&quot;]/div[@class=&quot;MuiBox-root css-h2do2k-UI-Plate-root-Auth-AccountRestrictedPlate-root&quot;]/div[@class=&quot;css-1t6x6g2&quot;]/button[@class=&quot;MuiTypography-root MuiTypography-p4 MuiLink-root MuiLink-underlineNone MuiLink-button css-1lfxrpm&quot;]</value>
      <webElementGuid>7da491a0-30b2-4d7f-8fa9-17d13cdf38d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>0345a252-c693-4080-bce5-11990ee95bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/button</value>
      <webElementGuid>da87489b-8655-47f8-8301-c47bd7195ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Создать новый подкаст'])[1]/preceding::button[1]</value>
      <webElementGuid>31c2729b-39f3-48a5-a615-53a1c4301383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Подтвердить']/parent::*</value>
      <webElementGuid>fecc7807-6ca4-4e99-912c-7e0a5f52971f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>9bd4ec67-c050-45e7-9318-3855315a1651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Подтвердить' or . = 'Подтвердить')]</value>
      <webElementGuid>c79e5b9c-3c98-40bf-bf8d-b2a4bf07b18e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
