<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>100 процентов импорта</name>
   <tag></tag>
   <elementGuidId>6d76b476-cb4a-4277-a3d5-43d9c7b48746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiTypography-root.MuiTypography-p3.css-qmt9wu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = '100%' or . = '100%')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f0cd291-d714-4df0-84ff-35cb9e5fa382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-p3 css-qmt9wu</value>
      <webElementGuid>58160288-886d-4bc6-93ea-8efe45bd6f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0%</value>
      <webElementGuid>a7c4a298-2cc2-4f2b-b1cc-032027c59787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-pr5jul-Main-root&quot;]/div[@class=&quot;MuiBox-root css-se72xl-Main-Content-root&quot;]/div[@class=&quot;MuiBox-root css-42igfv&quot;]/div[@class=&quot;MuiBox-root css-c3v8sx-Ui-Container-root&quot;]/div[@class=&quot;css-a2qr2c-Ui-Container-inner&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded MuiCard-root css-16f9hup-Podcasts-PodcastImporting-root&quot;]/span[@class=&quot;MuiTypography-root MuiTypography-p3 css-qmt9wu&quot;]</value>
      <webElementGuid>26290de0-45d3-4e70-9162-d14a47f04ef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div/div/div/div/span[3]</value>
      <webElementGuid>e3077bb0-2087-4ff5-8d32-1de86af2a306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ваш подкаст импортируется'])[1]/following::span[3]</value>
      <webElementGuid>2d0e2952-0411-4115-86c7-cfe6eaf6325f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить эпизод'])[1]/following::span[3]</value>
      <webElementGuid>0442c9c7-51ce-456c-ba14-03de93be902f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отменить импорт'])[1]/preceding::span[1]</value>
      <webElementGuid>f91bca9b-3152-4c34-833b-0a31bb964b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>1c35fb0e-9f90-4e6d-86a8-f5a3cd1ade2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>04f179b6-b69c-444d-a32c-9d12e71b6886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0%' or . = '0%')]</value>
      <webElementGuid>4aa8d92e-5dda-4238-ba30-48ca4618a988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
