<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Обложка</name>
   <tag></tag>
   <elementGuidId>45264c9c-8970-4cb5-a76e-2294c4db7ed5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@data-nimg = 'fill']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9d2aa81-e3f7-43d4-8671-7757ae52ebf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://st.zvuk.com/d/928638da-c65b-47c7-be51-0ce23d70817a/poster.png?</value>
      <webElementGuid>57d3c9df-7015-4a19-bec2-f6960985f4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a45011f6-3376-4177-8b9d-72f94500e141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>daa3a6ed-4e73-4c04-8e8c-207fe1bb5727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-almznq-Image-root</value>
      <webElementGuid>26a59027-8de8-4f01-ae93-4fccbf009b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-pr5jul-Main-root&quot;]/div[@class=&quot;MuiBox-root css-13xm5u6&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded MuiCard-root css-1agl10a&quot;]/div[@class=&quot;MuiCardContent-root css-drw0oh&quot;]/div[@class=&quot;css-fji96s-Podcasts-ImportPodcast-podcastInfo&quot;]/div[@class=&quot;MuiBox-root css-9bhw4k-Podcasts-ImportPodcast-imageWrap&quot;]/div[@class=&quot;MuiBox-root css-193jdwl-ImportPodcastPoster-root&quot;]/div[@class=&quot;MuiBox-root css-aybkh8-ImportPodcastPoster-posterContainer&quot;]/span[1]/img[@class=&quot;css-almznq-Image-root&quot;]</value>
      <webElementGuid>e3a299ad-9057-4234-8f9c-c177a1b7d786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[2]/div/div/div[4]/div/div/div/span/img</value>
      <webElementGuid>56275a8b-c9a1-4135-a23f-9b03fa726032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://st.zvuk.com/d/928638da-c65b-47c7-be51-0ce23d70817a/poster.png?')]</value>
      <webElementGuid>7030f23f-cb16-4eeb-b56f-948571169bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/span/img</value>
      <webElementGuid>bc3e25ce-6025-461d-bcdc-6930be6f3246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://st.zvuk.com/d/928638da-c65b-47c7-be51-0ce23d70817a/poster.png?']</value>
      <webElementGuid>3b67240f-fb80-4be0-9583-2040aa2a0f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
