<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Поле RSS</name>
   <tag></tag>
   <elementGuidId>6831e05a-c86c-4c18-b64b-571f404a1425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'rssLink']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'rssLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;rssLink&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86868d55-b150-4036-bfbb-f2396e64cac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>be9c6614-791e-43e8-a4c8-306fdccfbc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rssLink</value>
      <webElementGuid>18bab0e5-4ca3-4a2d-a2b0-2918880eb550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>https://example.com/rss</value>
      <webElementGuid>86980754-b4e0-465e-b050-907b58aee598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>099348da-cd8b-4c54-b877-91bb185e15ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input css-a1c9b9</value>
      <webElementGuid>37c4e901-7412-46b0-8648-503ace00d0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-pr5jul-Main-root&quot;]/div[@class=&quot;MuiBox-root css-13xm5u6&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded MuiCard-root css-1agl10a&quot;]/div[@class=&quot;MuiCardContent-root css-drw0oh&quot;]/div[@class=&quot;MuiFormControl-root MuiFormControl-fullWidth MuiTextField-root css-1a9k5qh-Podcasts-ImportPodcast-input&quot;]/div[@class=&quot;MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl css-1ty88a9&quot;]/input[@class=&quot;MuiOutlinedInput-input MuiInputBase-input css-a1c9b9&quot;]</value>
      <webElementGuid>92f35a8b-4ab1-4d79-9c50-44701046ee88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='rssLink']</value>
      <webElementGuid>1baba2af-3ac6-437e-8b34-31d321f2e7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>39ba126c-1df7-476f-b23b-5dca9dbfe32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3914e4c1-1f7c-4094-9582-3c9b7270b76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rssLink' and @placeholder = 'https://example.com/rss' and @type = 'text']</value>
      <webElementGuid>430300a9-165e-4885-bc44-9bd36757ef58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
