<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Заголовок2</name>
   <tag></tag>
   <elementGuidId>65043126-858d-4663-a850-3af43601d905</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/h2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.MuiTypography-root.MuiTypography-p4.MuiTypography-alignCenter.css-nvrurw</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c48d3f7d-7e27-473f-9afb-174b393c8187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-p4 MuiTypography-alignCenter css-nvrurw</value>
      <webElementGuid>ac10d10b-c23c-4a5a-bdbf-34a2f2d6d914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>На вашу почту vvaku@mailto.plus было отправлено письмо.</value>
      <webElementGuid>7cfbd372-9e85-476b-ab02-6931a873da9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiModal-root MuiDialog-root css-126xj0f&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm css-cmr8ls-Auth-EmailConfirmModal-paper&quot;]/div[@class=&quot;MuiDialogContent-root css-12wk1pa&quot;]/form[1]/h2[@class=&quot;MuiTypography-root MuiTypography-p4 MuiTypography-alignCenter css-nvrurw&quot;]</value>
      <webElementGuid>4de6a0a1-eaa2-4263-9cf2-5bf894d470a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Подтверждение почты'])[1]/following::h2[1]</value>
      <webElementGuid>e1f051a3-1b92-4f5c-b565-7b3e6d36c244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Почта для связи со службой поддержки - support@zvuk.com'])[1]/following::h2[2]</value>
      <webElementGuid>09d64b41-d53e-4b15-acd4-2f303dad529e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Код из письма'])[1]/preceding::h2[1]</value>
      <webElementGuid>2b1c4f14-c086-48a0-ab3d-d521ae1a94e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='На вашу почту']/parent::*</value>
      <webElementGuid>95b3dcbc-3b20-46fd-964d-66b249299054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/h2</value>
      <webElementGuid>0ccad6fc-2b98-4c8c-85f3-e77d0beea451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'На вашу почту vvaku@mailto.plus было отправлено письмо.' or . = 'На вашу почту vvaku@mailto.plus было отправлено письмо.')]</value>
      <webElementGuid>4b8135e5-0680-4409-9233-bd62200c6fc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
