<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ОтправитьЗаново</name>
   <tag></tag>
   <elementGuidId>293503d8-41bb-4846-ac1c-cbb0b90221b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Отправить заново' or . = 'Отправить заново')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiTypography-root.MuiTypography-p4.MuiLink-root.MuiLink-underlineNone.MuiLink-button.css-12bvdc3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c22b64c0-beb9-4d54-9ed2-5283dcced795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-p4 MuiLink-root MuiLink-underlineNone MuiLink-button css-12bvdc3</value>
      <webElementGuid>a092d5f5-781a-4e08-8f27-31084b7175e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87d36aec-5d03-4188-a651-fa8b85e592bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Отправить заново</value>
      <webElementGuid>a35804bc-238c-48e5-b02d-211bdc2b3d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiModal-root MuiDialog-root css-126xj0f&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm css-cmr8ls-Auth-EmailConfirmModal-paper&quot;]/div[@class=&quot;MuiDialogContent-root css-12wk1pa&quot;]/form[1]/div[@class=&quot;css-1jhuvj7&quot;]/button[@class=&quot;MuiTypography-root MuiTypography-p4 MuiLink-root MuiLink-underlineNone MuiLink-button css-12bvdc3&quot;]</value>
      <webElementGuid>0d6fec26-f699-4162-82b5-4f95da3cd79f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>d28cf331-4137-4060-a078-be03c9b62c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Подтвердить'])[2]/following::button[1]</value>
      <webElementGuid>2fb35e04-3991-4ae7-82f7-ce5ebe40183f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Код из письма'])[1]/following::button[2]</value>
      <webElementGuid>db86ff76-89d3-4707-82b7-e8939e54d989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Отправить заново']/parent::*</value>
      <webElementGuid>d4736260-2233-44bc-a55a-36056946cd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>d249cabb-d077-4685-bdcc-f363c9dc8335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Отправить заново' or . = 'Отправить заново')]</value>
      <webElementGuid>0e20ea44-7b12-4294-8fbb-8e78d10a6fe3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
