<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Комментарий к блокировке</name>
   <tag></tag>
   <elementGuidId>552603c7-e2f1-4ce6-809b-a41a7ceb6e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='comment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;comment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5f86551a-3184-42dd-8dd8-53488485c52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f720185e-9613-4803-9b98-62c0be47130e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>b953380c-0855-45ff-bd98-5b7cc8fb8af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-comment</value>
      <webElementGuid>0f33b591-2153-4509-a905-d4c51a9fa3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>ffc0efd1-c6e8-4879-b79f-2b9922fc652c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputMultiline css-tjh4c4</value>
      <webElementGuid>607ff9e1-593f-4cc8-9fdd-012755b924a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiModal-root MuiDialog-root css-1tder41-Modal-root&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper css-16u656j&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation24 Modal-paper MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthSm css-1rx4q0r&quot;]/div[@class=&quot;MuiDialogContent-root css-1h0u45g&quot;]/form[@class=&quot;css-x5ofyh-PodcasterForm-form&quot;]/div[@class=&quot;MuiFormControl-root MuiFormControl-marginNormal MuiFormControl-fullWidth MuiTextField-root css-on2w7h&quot;]/div[@class=&quot;MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-fullWidth Mui-focused MuiInputBase-formControl MuiInputBase-multiline css-15tlwyi&quot;]/textarea[@class=&quot;MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputMultiline css-tjh4c4&quot;]</value>
      <webElementGuid>b4055c81-e8fc-4072-8a29-4e72de532b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='comment']</value>
      <webElementGuid>08eaa750-01fc-4eaf-9d8b-bd201449bd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>93d12826-1a9c-4c3a-b5a8-4a4af75edf25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'comment' and @form = '[object Object]']</value>
      <webElementGuid>d55935a9-8941-4ff5-b062-f09eee1356ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
