<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ИмяАвтора</name>
   <tag></tag>
   <elementGuidId>5abc52a8-cabb-4412-b38a-c93b17d8fd0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authorName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='authorName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>698a6d6a-9b01-47b1-ac0b-dfdf6de7ee3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>04ab6c87-6e08-4d59-9778-f7aa1d8954df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authorName</value>
      <webElementGuid>c903d3b5-fadb-4217-8ebb-e50c56a6f9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>authorName</value>
      <webElementGuid>64ecf256-0447-4c7e-8425-e4166bd7fd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4891fd7-28dd-4901-a5f4-d7fceceaadbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input css-a1c9b9</value>
      <webElementGuid>9214b797-e921-4858-b9a1-96a9f5d95426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authorName&quot;)</value>
      <webElementGuid>aaf92b60-c020-43da-b000-241d16448b9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='authorName']</value>
      <webElementGuid>cff71874-656a-4bf8-8fad-e706b7db7b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[3]/div/div/form/div[2]/div[5]/div[4]/div/input</value>
      <webElementGuid>fb000b98-dfe5-448f-82bb-30692aa062df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a66308d2-8405-477d-a7b4-31989d33dc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'authorName' and @name = 'authorName' and @type = 'text']</value>
      <webElementGuid>1a081e9f-0f16-4690-97a5-49609fa36902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
