<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>КатегорияБизнес</name>
   <tag></tag>
   <elementGuidId>9a7610a9-0e5f-406a-8fbd-aea9df88fefd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.MuiMenuItem-root.MuiMenuItem-gutters.MuiButtonBase-root.css-1u7utvn-MenuItem-Select-menuItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'Бизнес' or . = 'Бизнес')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3a4e4423-86f0-4ae0-ad64-7c3d43054401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-1u7utvn-MenuItem-Select-menuItem</value>
      <webElementGuid>57dae50f-1b2f-47bb-a418-eb6d80f52e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3aafa126-f9fb-42db-8aae-1202cc83ef42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>446ecb8a-8724-45b9-bf79-d94d4c813482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8b3d5e70-5a50-4d3a-ab6c-60f3143dd0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Бизнес</value>
      <webElementGuid>d8d15801-dec1-4b34-b97a-e45a560f927f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-podcastCategories[0].category&quot;)/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiMenu-paper MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiPopover-paper css-1bti4fz&quot;]/ul[@class=&quot;MuiList-root MuiList-padding MuiMenu-list css-1tatuml&quot;]/li[@class=&quot;MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-1u7utvn-MenuItem-Select-menuItem&quot;]</value>
      <webElementGuid>42d8232c-8f89-43ae-81f4-f4e5fdbe8db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-podcastCategories[0].category']/div[3]/ul/li</value>
      <webElementGuid>fc86e169-5880-43bc-8543-30cb91984ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Принять'])[1]/following::li[2]</value>
      <webElementGuid>de189809-9539-4899-b7b1-d2b8aaec7324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Государство'])[1]/preceding::li[1]</value>
      <webElementGuid>0de42754-43dd-4ef4-afa8-7682cb989b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Дети и семья'])[1]/preceding::li[2]</value>
      <webElementGuid>b493d8ea-c021-4cdc-9e4f-5f0fb0a8e2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Бизнес']/parent::*</value>
      <webElementGuid>baa7255d-36d5-4ccb-931c-2e54c9d92073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li</value>
      <webElementGuid>9fb85d67-fd67-4e26-b91d-d21e2814f45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Бизнес' or . = 'Бизнес')]</value>
      <webElementGuid>a3a25bf1-b891-4924-b09d-ff1b3063651e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
