<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Название мини-сайта</name>
   <tag></tag>
   <elementGuidId>b4fea6ce-b596-4af9-b566-bc6556bc2f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;urlSitePrefix&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'urlSitePrefix' and @placeholder = 'Название мини-сайта *']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='urlSitePrefix']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08453b40-63cc-44e0-b0a8-cd661c0cdb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a0714da-ca5a-4bb0-b964-bb99630f2d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d0b2698-49a3-40ca-83df-2d0248adbe93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>urlSitePrefix</value>
      <webElementGuid>cd11533e-7663-4415-8f2b-c1dc867947be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Название мини-сайта *</value>
      <webElementGuid>e179c75a-c07c-4530-8f87-02c649fa61d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiOutlinedInput-input MuiInputBase-input css-a1c9b9</value>
      <webElementGuid>bd22bf01-e90b-4fe7-b5b2-8e5ff01c4bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-pr5jul-Main-root&quot;]/div[@class=&quot;MuiBox-root css-se72xl-Main-Content-root&quot;]/div[@class=&quot;MuiBox-root css-c3v8sx-Ui-Container-root&quot;]/div[@class=&quot;css-1gqp5wz-Ui-Container-inner&quot;]/form[1]/div[@class=&quot;css-gg7qas&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded  css-180rw0y-Podcasts-ContentSection-root&quot;]/div[@class=&quot;css-1n7x17v-Podcasts-PodcastInfoForm-domain&quot;]/div[@class=&quot;MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary Mui-error Mui-focused css-138919f&quot;]/input[@class=&quot;MuiOutlinedInput-input MuiInputBase-input css-a1c9b9&quot;]</value>
      <webElementGuid>ee57dee5-ec8a-4039-8e50-1918e5c9425d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='urlSitePrefix']</value>
      <webElementGuid>eac5c9d3-787f-4f5f-abb4-5c412f8249c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div/div[2]/div/form/div/div/div[3]/div[2]/input</value>
      <webElementGuid>98d55798-d1f8-44f2-972a-b3c355dc1ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>557fe477-6f60-4596-ab7d-83e470edbef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'urlSitePrefix' and @placeholder = 'Название мини-сайта *']</value>
      <webElementGuid>813b9cc4-ff47-40b9-966f-7b2333b72c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
