<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Описание</name>
   <tag></tag>
   <elementGuidId>78fefbab-f4be-4f6f-a0e7-a888becb2049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.notranslate.public-DraftEditor-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@role = 'textbox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'textbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f32839fb-5736-4de6-964f-f6d062683d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>describe</value>
      <webElementGuid>535a568f-a59e-4e76-8526-980f6b2805ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>733baf3c-dd96-4520-b0d8-4324fbab65b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>08dba8a8-9ce4-49eb-8bc2-47b986f6d589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>db3774e7-eb9b-4661-8854-cd008bf383eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>notranslate public-DraftEditor-content</value>
      <webElementGuid>2e981acf-e9f4-4193-988e-ea66978b8612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e68dce3-6d5b-47cc-a19a-eeac295dfc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>195da912-fcc5-44ae-8b5b-725f342acbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f488525-8987-43a0-910c-a183ce027519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Описание</value>
      <webElementGuid>2fb9c478-b570-4f93-9836-36a4f7d8e61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-a1abyh-Main-root&quot;]/div[@class=&quot;Ui-Container-withPadding MuiBox-root css-c3v8sx-Ui-Container-root&quot;]/div[@class=&quot;css-1972p4d-Ui-Container-inner&quot;]/div[@class=&quot;MuiBox-root css-1yyt10r&quot;]/form[1]/div[@class=&quot;css-gg7qas&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded  css-180rw0y-Podcasts-ContentSection-root&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-15gofbp-Editor-wrapper&quot;]/div[@class=&quot;MuiBox-root css-1tszyam-Editor-content&quot;]/div[@class=&quot;DraftEditor-root&quot;]/div[@class=&quot;DraftEditor-editorContainer&quot;]/div[@class=&quot;notranslate public-DraftEditor-content&quot;]</value>
      <webElementGuid>dcffbb56-293e-4bd3-a410-894274abbe4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[3]/div/div/form/div[2]/div/div[5]/div/div[2]/div/div/div</value>
      <webElementGuid>25cc5904-8834-4932-b12e-ec40c1b30ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[9]</value>
      <webElementGuid>8b799e11-2b39-4a1a-b832-48e482ae21a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://st.zvq.me/'])[1]/following::div[10]</value>
      <webElementGuid>b4910ef2-4f08-4d87-9534-a714711e8161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Загрузить изображение'])[1]/preceding::div[5]</value>
      <webElementGuid>51afb436-531e-4c11-b097-1b99bd019fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div</value>
      <webElementGuid>12869adc-f5a7-4ac0-aef4-1fb1f5a4dcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Описание' or . = 'Описание')]</value>
      <webElementGuid>9fb4234c-9a9d-4b73-b863-839846b2c299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
