<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ПодкатегорияИнвестиции</name>
   <tag></tag>
   <elementGuidId>dcbbd22e-bbb1-4f43-8f7b-9934e7a17ea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.MuiMenuItem-root.MuiMenuItem-gutters.MuiButtonBase-root.css-1u7utvn-MenuItem-Select-menuItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'Инвестиции' or . = 'Инвестиции')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7f13669f-ff4a-4b1e-9e6e-30d5fd6e7dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-1u7utvn-MenuItem-Select-menuItem</value>
      <webElementGuid>5fe5a03d-bb97-4f5d-91dd-2f599eaba8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf05eb6e-ee3b-48a4-9e51-9277ce0b27fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a7e6c68c-c4a5-47de-89f4-19aa4d1be296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>1f69eb97-62c7-48c0-99bd-e844625b4d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Инвестиции</value>
      <webElementGuid>222d9c46-e3e9-4769-8df2-d99f6d05c5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-podcastCategories[0].subcategory&quot;)/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiMenu-paper MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiPopover-paper css-1bti4fz&quot;]/ul[@class=&quot;MuiList-root MuiList-padding MuiMenu-list css-1tatuml&quot;]/li[@class=&quot;MuiMenuItem-root MuiMenuItem-gutters MuiButtonBase-root css-1u7utvn-MenuItem-Select-menuItem&quot;]</value>
      <webElementGuid>74dbd3b1-c021-466a-bd4c-1b28d99252e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-podcastCategories[0].subcategory']/div[3]/ul/li</value>
      <webElementGuid>335aa1d8-feb2-44c3-abf4-4a10da47d42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Принять'])[1]/following::li[2]</value>
      <webElementGuid>831b9fc4-97fa-44e1-9bfc-895cc404bef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Карьера'])[1]/preceding::li[1]</value>
      <webElementGuid>2318f25f-b7ec-40a4-87c9-c1f6a4c74200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Маркетинг'])[1]/preceding::li[2]</value>
      <webElementGuid>ea3ce708-7300-4598-a262-247678a99685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Инвестиции']/parent::*</value>
      <webElementGuid>4e95c3db-8e0a-4027-aeb0-0719981f4345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li</value>
      <webElementGuid>f3e3abfe-11b9-4282-9768-003fedf1ec56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Инвестиции' or . = 'Инвестиции')]</value>
      <webElementGuid>654e27d3-0b72-4f4c-bcc3-e8cd57a73c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
