<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Сохранить и посмотреть</name>
   <tag></tag>
   <elementGuidId>4e3b629b-b6c0-44ec-bb44-14f184a45373</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-disableElevation.MuiButtonBase-root.css-1dm8yx0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'submit' and (text() = 'Сохранить и посмотреть' or . = 'Сохранить и посмотреть')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b56581a7-806d-49c9-814a-90ba854fd89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-1dm8yx0</value>
      <webElementGuid>71e8b5da-e49f-4ce0-b810-bb555c4a42a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>885f9eb1-3ae2-4633-8a23-019c8a4b101e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4c3cd110-ea89-4235-b097-948bedd07dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Сохранить и посмотреть</value>
      <webElementGuid>2b2ed3f1-d03a-4e0f-bbf8-e28e3148f3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-3dyzvh-Layout-root&quot;]/main[@class=&quot;MuiBox-root css-a1abyh-Main-root&quot;]/div[@class=&quot;Ui-Container-withPadding MuiBox-root css-c3v8sx-Ui-Container-root&quot;]/div[@class=&quot;css-1972p4d-Ui-Container-inner&quot;]/div[@class=&quot;MuiBox-root css-1yyt10r&quot;]/form[1]/div[@class=&quot;css-gg7qas&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-blur MuiPaper-rounded  css-180rw0y-Podcasts-ContentSection-root&quot;]/div[@class=&quot;css-1xhj18k&quot;]/button[@class=&quot;MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-1dm8yx0&quot;]</value>
      <webElementGuid>5853d0fd-b0c8-41d5-9331-1156b2bd0437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>91d0f96d-920d-49d5-b074-12cbf2dd7b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/main/div[3]/div/div/form/div[2]/div[6]/div[4]/button</value>
      <webElementGuid>81869f30-7664-4dca-a0aa-64247861edb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='о создании нового подкаста'])[1]/following::button[1]</value>
      <webElementGuid>4638acc2-1ec3-4d9c-a853-a24a82a9278f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Сохранить и посмотреть']/parent::*</value>
      <webElementGuid>52d2dcc3-60fa-4886-984a-20c19c03c256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[4]/button</value>
      <webElementGuid>6c913a25-b899-4881-aa64-f33559035e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Сохранить и посмотреть' or . = 'Сохранить и посмотреть')]</value>
      <webElementGuid>614cb41b-5578-4d0a-9ba3-c33c3d6f2c55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
